TITLE[0]="No instrumentation"
TITLE[1]="Kieker with AspectJ"
TITLE[2]="Kieker with Source Instrumentation"
TITLE[3]="Kieker with Source Instrumentation and CircularFifoQueue"
TITLE[4]="Kieker with Source Instrumentation and DurationRecord"
TITLE[5]="Kieker with Source Instrumentation, DurationRecord and CircularFifoQueue"
TITLE[6]="Kieker with Source Instrumentation and DurationRecord and Aggregation"
TITLE[7]="Kieker with Source Instrumentation, CircularFifoQueue, DurationRecord and Aggregation"
