TITLE[0]="No instrumentation"
TITLE[1]="Kieker with AspectJ"
TITLE[2]="Kieker with Source Instrumentation"
TITLE[3]="Kieker with Source Instrumentation and DurationRecord"
TITLE[4]="Kieker with Source Instrumentation and DurationRecord and Aggregation"
