---
name: Run Exponential Size Comparison
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: 0 */8 * * *

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        java:
          - 11
          - 17
          - 21
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: Java ${{ matrix.java }} OS ${{ matrix.os }} sample
    timeout-minutes: 15 # For check of functional runnability, 15 minutes should be more than sufficient, otherwise, developer should be notified
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Get DiSL
        run: |
          cd ../
          git clone https://gitlab.ow2.org/disl/disl.git
          ant
          mvn install:install-file -Dfile=output/lib/disl-server.jar -DgroupId=ch.usi.dag -DartifactId=disl -Dversion=1.0-SNAPSHOT -Dpackaging=jar
          export DISL_HOME=$(pwd)
      - name: Run minimal parameter experiment and check success
        run: |
          export SLEEP_TIME=0
          export NUM_OF_LOOPS=1 
          export TOTAL_NUM_OF_CALLS=10 
          export RECURSION_DEPTH=10 
          export EXPONENTIAL_SIZES="2 4"
          export DISL_HOME=../disl
          ./runDiSLExperiment.sh
          SIResults=$(ls frameworks/SI-exp-results/ | grep .zip | wc -l) 
          if [ $SIResults -ne 2 ] 
          then
            echo "It should be 2 results for source instrumentation, but was $SIResults"
            exit 1
          fi
          
          AspectJResults=$(ls frameworks/AspectJ-exp-results/ | grep .zip | wc -l) 
          if [ $SIResults -ne 2 ] 
          then
            echo "It should be 2 results for AspectJ, but was $AspectJResults"
            exit 1
          fi
